version: '2'
services:
    web:
        image: httpd:alpine
        ports:
            - "80:80"
        volumes:
            - ./html:/usr/local/apache2/htdocs
            - ./extra:/usr/local/apache2/conf/extra

    php7:
        image: php:7-fpm-alpine
        volumes:
            - ./html:/var/www/html
    db:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - ./data_dir:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 3306:80
      environment:
        - PMA_HOST=db
