version: '2'
services:
    web:
        hostname: web
        image: httpd:alpine
        ports:
            - "80:80"
        volumes:
            - ./html:/usr/local/apache2/htdocs
            - ./conf:/usr/local/apache2/conf
        depends_on:
            - php7



    php7:
        hostname: php7
        image: php:7-fpm-alpine
        volumes:
            - ./html:/var/www/html
        networks:
          default:
            aliases:
              - example.local
    db:
        hostname: db
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: password
        volumes:
          - ./data_dir:/var/lib/mysql

    phpmyadmin:
        hostname: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
          - 3306:80
        environment:
          - PMA_HOST=db
